### ISSUE TITLE
mpl, эпизод 3 : данные на графиках

### ISSUE THREAD

**Issue by avasyukov** [Abrackadabrr/PythonLabs#1]
Кажется, данные жёстко потеряны. Части препов нет вообще, в группах нездорово мало людей.

**Comment by Abrackadabrr** [comment]
Я тестировал свой код на предмет общности для разного типа данных (насколько код независим от входных данных) и удалил где-то половину файла для этой самой проверки. Извиняюсь, не увидел, когда коммитил, сделаю перезалив

**Comment by Abrackadabrr** [comment]
Обновил данные и график
